language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=coverage
install:
  - pip install --upgrade tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
